# gateway.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: web-demo
  annotations:
    # cert-manager will watch this and issue a certificate
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: envoy
  listeners:
    # HTTP listener - needed for ACME HTTP-01 challenge
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    # HTTPS listener
    - name: https
      port: 443
      protocol: HTTPS
      hostname: "${DOMAIN}"
      # hostname: "*.${DOMAIN}"
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - name: ${DOMAIN_CERT_NAME}-tls # cert-manager creates this secret
    # HTTPS listener - API
    - name: api
      port: 443
      protocol: HTTPS
      hostname: "api.${DOMAIN}"
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - name: ${DOMAIN_CERT_NAME}-tls # cert-manager creates this secret
    # HTTPS listener - API
    - name: static
      port: 443
      protocol: HTTPS
      hostname: "static.${DOMAIN}"
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - name: ${DOMAIN_CERT_NAME}-tls # cert-manager creates this secret
