# The Service Account (Must match the name in the OpenBao Role)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-sa
  namespace: default
---
# The SecretStore (Defines the connection)
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao-store
  namespace: default
spec:
  provider:
    vault:
      # Address of OpenBao service inside the cluster
      server: "http://openbao-active.openbao.svc.cluster.local:8200"
      path: "secret"
      version: "v2" # We are using KV-v2
      auth:
        # Authenticate using the Kubernetes Service Account we just created
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-role"
          serviceAccountRef:
            name: "eso-sa"
