#cloud-config
package_update: true
package_upgrade: true

packages:
  - jq
  - build-essential
  - python3-pip
  - python3-venv

runcmd:
  # Disable SSH password authentication for security
  - sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i 's/^#*ChallengeResponseAuthentication.*/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config
  - sed -i 's/^#*KbdInteractiveAuthentication.*/KbdInteractiveAuthentication no/' /etc/ssh/sshd_config
  - systemctl restart sshd
  # Install nvidia_gpu_exporter
  - |
    cd /tmp
    wget https://github.com/utkuozdemir/nvidia_gpu_exporter/releases/download/v1.4.1/nvidia-gpu-exporter_1.4.1_linux_amd64.deb
    dpkg -i nvidia-gpu-exporter_1.4.1_linux_amd64.deb
  # Install NVIDIA drivers - CUDA 12.8 for Ubuntu 24.04 - https://developer.nvidia.com/cuda-12-8-1-download-archive
  - |
    export DEBIAN_FRONTEND=noninteractive
    apt install -y linux-headers-$(uname -r)
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
    dpkg -i cuda-keyring_1.1-1_all.deb
    apt-get update
    apt-get -y install cuda-toolkit-12-8
    apt-get install -y nvidia-open
    apt-get install -y nvtop
    reboot
